services:
  localdb:
    container_name: EurekaHps
    image: mysql:8.0
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: Eureka
      MYSQL_DATABASE: hps
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
      - --innodb_ft_server_stopword_table=testdb/StopWord

    volumes:
      - ./mysql:/var/lib/mysql
      # - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
